version: '3.8'

services:
  db:
    image: postgres:15
    container_name: master_db
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    ports:
      - "6800:6800"
    env_file:
      - .env
    volumes:
      - ./app:/app

volumes:
  postgres_data:
